//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeMateriais.Exceptions.ExceptionBase {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeMateriais.Exceptions.ExceptionBase.ErrorMessagesResource", typeof(ErrorMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitida a alteração do código de barras..
        /// </summary>
        public static string ALTERACAO_CODIGO_BARRAS_NAO_PERMITIDA {
            get {
                return ResourceManager.GetString("ALTERACAO_CODIGO_BARRAS_NAO_PERMITIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitida a alteração da matrícula..
        /// </summary>
        public static string ALTERACAO_MATRICULA_NAO_PERMITIDA {
            get {
                return ResourceManager.GetString("ALTERACAO_MATRICULA_NAO_PERMITIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria inválida..
        /// </summary>
        public static string CATEGORIA_INVALIDA {
            get {
                return ResourceManager.GetString("CATEGORIA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de barras já cadastrado..
        /// </summary>
        public static string CODIGO_BARRAS_CADASTRADO {
            get {
                return ResourceManager.GetString("CODIGO_BARRAS_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de barras em branco..
        /// </summary>
        public static string CODIGO_BARRAS_EM_BRANCO {
            get {
                return ResourceManager.GetString("CODIGO_BARRAS_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de barras inválido..
        /// </summary>
        public static string CODIGO_BARRAS_INVALIDO {
            get {
                return ResourceManager.GetString("CODIGO_BARRAS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de dígitos do código de barras é inválido..
        /// </summary>
        public static string CODIGO_BARRAS_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("CODIGO_BARRAS_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado está expirado..
        /// </summary>
        public static string CODIGO_EXPIRADO {
            get {
                return ResourceManager.GetString("CODIGO_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado não confere ao enviado ao e-mail cadastrado..
        /// </summary>
        public static string CODIGOS_NAO_CONFEREM {
            get {
                return ResourceManager.GetString("CODIGOS_NAO_CONFEREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum colaborador foi localizado com os dados informados..
        /// </summary>
        public static string COLABORADOR_NAO_LOCALIZADO {
            get {
                return ResourceManager.GetString("COLABORADOR_NAO_LOCALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi localizada nenhuma concessão para o código informado..
        /// </summary>
        public static string CONCESSAO_NAO_LOCALIZADA {
            get {
                return ResourceManager.GetString("CONCESSAO_NAO_LOCALIZADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já cadastrado..
        /// </summary>
        public static string CPF_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o CPF..
        /// </summary>
        public static string CPF_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("CPF_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF informado é inválido..
        /// </summary>
        public static string CPF_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do material em branco..
        /// </summary>
        public static string DESCRICAO_EM_BRANCO {
            get {
                return ResourceManager.GetString("DESCRICAO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail já cadastrado..
        /// </summary>
        public static string EMAIL_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o email do colaborador..
        /// </summary>
        public static string EMAIL_COLABORADOR_EM_BRANCO {
            get {
                return ResourceManager.GetString("EMAIL_COLABORADOR_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail do colaborador inválido..
        /// </summary>
        public static string EMAIL_COLABORADOR_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_COLABORADOR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum e-mail localizado..
        /// </summary>
        public static string EMAIL_NAO_LOCALIZADO {
            get {
                return ResourceManager.GetString("EMAIL_NAO_LOCALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o e-mail..
        /// </summary>
        public static string EMAIL_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail informado inválido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao se comunicar com serviço de e-mail, por favor, tente novamente..
        /// </summary>
        public static string ERRO_AO_ENVIAR_EMAIL {
            get {
                return ResourceManager.GetString("ERRO_AO_ENVIAR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário e/ou senha incorretos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula já cadastrada..
        /// </summary>
        public static string MATRICULA_CADASTRADA {
            get {
                return ResourceManager.GetString("MATRICULA_CADASTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe a matrícula do colaborador..
        /// </summary>
        public static string MATRICULA_COLABORADOR_EM_BRANCO {
            get {
                return ResourceManager.GetString("MATRICULA_COLABORADOR_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A matrícula informada é inválida..
        /// </summary>
        public static string MATRICULA_COLABORADOR_INVALIDO {
            get {
                return ResourceManager.GetString("MATRICULA_COLABORADOR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum material foi localizado com os dados informados..
        /// </summary>
        public static string NENHUM_MATERIAL_LOCALIZADO {
            get {
                return ResourceManager.GetString("NENHUM_MATERIAL_LOCALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o nickname do colaborador..
        /// </summary>
        public static string NICKNAME_COLABORADOR_EM_BRANCO {
            get {
                return ResourceManager.GetString("NICKNAME_COLABORADOR_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o nome do colaborador..
        /// </summary>
        public static string NOME_COLABORADOR_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOME_COLABORADOR_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o nome do material..
        /// </summary>
        public static string NOME_MATERIAL_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOME_MATERIAL_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o nome..
        /// </summary>
        public static string NOME_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOME_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe a nova senha..
        /// </summary>
        public static string NOVA_SENHA_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOVA_SENHA_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha deve conter ao menos seis caracteres..
        /// </summary>
        public static string NOVA_SENHA_SEIS_CARACTERES {
            get {
                return ResourceManager.GetString("NOVA_SENHA_SEIS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe a senha do colaborador..
        /// </summary>
        public static string SENHA_COLABORADOR_EM_BRANCO {
            get {
                return ResourceManager.GetString("SENHA_COLABORADOR_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter ao menos seis caracteres..
        /// </summary>
        public static string SENHA_COLABORADOR_MINIMO_SEIS_CARACTERES {
            get {
                return ResourceManager.GetString("SENHA_COLABORADOR_MINIMO_SEIS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter ao menos seis caracteres..
        /// </summary>
        public static string SENHA_MINIMO_SEIS_CARACTERES {
            get {
                return ResourceManager.GetString("SENHA_MINIMO_SEIS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe a senha..
        /// </summary>
        public static string SENHA_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas digitadas não são iguais..
        /// </summary>
        public static string SENHAS_NAO_CONFEREM {
            get {
                return ResourceManager.GetString("SENHAS_NAO_CONFEREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o telefone..
        /// </summary>
        public static string TELEFONE_COLABORADOR_EM_BRANCO {
            get {
                return ResourceManager.GetString("TELEFONE_COLABORADOR_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone informado é inválido..
        /// </summary>
        public static string TELEFONE_COLABORADOR_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_COLABORADOR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o telefone..
        /// </summary>
        public static string TELEFONE_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("TELEFONE_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone informado é inválido..
        /// </summary>
        public static string TELEFONE_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token expirado..
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token inválido..
        /// </summary>
        public static string TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não localizado..
        /// </summary>
        public static string USUARIO_NAO_LOCALIZADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_LOCALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário sem permissão.
        /// </summary>
        public static string USUARIO_SEM_PREMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PREMISSAO", resourceCulture);
            }
        }
    }
}
